ARG DEV_IMAGE
FROM ${DEV_IMAGE} as dev
ARG SERVICE_NAME

FROM alpine:3.9
ARG SERVICE_NAME
ENV SERVICE_NAME ${SERVICE_NAME}

COPY docker/docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

COPY --from=dev /go/bin/${SERVICE_NAME} /usr/local/bin/${SERVICE_NAME}
COPY --from=dev /go/src/geodb/ /home/${SERVICE_NAME}/geodb/

ENTRYPOINT [ "docker-entrypoint.sh" ]